# 4. NUOVO VIVA IMPARARE 4
puts "\n📚 Creazione corso: Nuovo Viva Imparare"
nvi = Corso.create!(
  nome: "Nuovo Viva Imparare",
  codice: "nvi",
  descrizione: "Sussidiario delle discipline per la scuola primaria"
)

nvi_volume4 = nvi.volumi.create!(
  nome: "Nuovo Viva Imparare 4",
  classe: 4,
  posizione: 4
)

# Matematica
nvi_matematica = nvi_volume4.discipline.create!(
  nome: "Matematica",
  codice: "mat",
  colore: "#A855F7"
)

[
  { numero: 1, titolo: "Copertina", slug: "nvi4_mat_p001", view_template: "nvi4_mat_p001", sottotitolo: "", base_color: "pink" },
  { numero: 2, titolo: "", slug: "nvi4_mat_p002", view_template: "nvi4_mat_p002", sottotitolo: "INDICE", base_color: "pink" },
  { numero: 3, titolo: "", slug: "nvi4_mat_p003", view_template: "nvi4_mat_p003", sottotitolo: "INDICE", base_color: "pink" },
  { numero: 4, titolo: "Numeri", slug: "nvi4_mat_p004", view_template: "nvi4_mat_p004", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 5, titolo: "La Linea dei Numeri", slug: "nvi4_mat_p005", view_template: "nvi4_mat_p005", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 6, titolo: "Operazioni", slug: "nvi4_mat_p006", view_template: "nvi4_mat_p006", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 7, titolo: "Moltiplicazione e Divisione", slug: "nvi4_mat_p007", view_template: "nvi4_mat_p007", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 8, titolo: "Problemi", slug: "nvi4_mat_p008", view_template: "nvi4_mat_p008", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 9, titolo: "Problemi con Dati Inutili e Nascosti", slug: "nvi4_mat_p009", view_template: "nvi4_mat_p009", sottotitolo: "PER RICOMINCIARE...", base_color: "pink" },
  { numero: 10, titolo: "NUMERI", slug: "nvi4_mat_p010", view_template: "nvi4_mat_p010", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 11, titolo: "NUMERI", slug: "nvi4_mat_p011", view_template: "nvi4_mat_p011", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 12, titolo: "Il Nostro Sistema di Numerazione", slug: "nvi4_mat_p012", view_template: "nvi4_mat_p012", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 13, titolo: "Cifre e Numeri", slug: "nvi4_mat_p013", view_template: "nvi4_mat_p013", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 14, titolo: "Il Nostro Sistema di Numerazione", slug: "nvi4_mat_p014", view_template: "nvi4_mat_p014", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 15, titolo: "I Numeri con le Migliaia", slug: "nvi4_mat_p015", view_template: "nvi4_mat_p015", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 16, titolo: "Scrivere e Leggere i Numeri", slug: "nvi4_mat_p016", view_template: "nvi4_mat_p016", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 17, titolo: "I Numeri", slug: "nvi4_mat_p017", view_template: "nvi4_mat_p017", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 18, titolo: "I Numeri e gli Egizi", slug: "nvi4_mat_p018", view_template: "nvi4_mat_p018", sottotitolo: "ARCHEOKIDS", base_color: "pink" },
  { numero: 19, titolo: "I Numeri e gli Egizi", slug: "nvi4_mat_p019", view_template: "nvi4_mat_p019", sottotitolo: "ARCHEOKIDS", base_color: "pink" },
  { numero: 20, titolo: "Ordinare i Numeri", slug: "nvi4_mat_p020", view_template: "nvi4_mat_p020", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 21, titolo: "Confrontare i Numeri", slug: "nvi4_mat_p021", view_template: "nvi4_mat_p021", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 22, titolo: "Arrotondamento o Approssimazione", slug: "nvi4_mat_p022", view_template: "nvi4_mat_p022", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 23, titolo: "Arrotondamento o Approssimazione", slug: "nvi4_mat_p023", view_template: "nvi4_mat_p023", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 24, titolo: "I Numeri", slug: "nvi4_mat_p024", view_template: "nvi4_mat_p024", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 25, titolo: "I Numeri", slug: "nvi4_mat_p025", view_template: "nvi4_mat_p025", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 26, titolo: "L'Addizione", slug: "nvi4_mat_p026", view_template: "nvi4_mat_p026", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 27, titolo: "L'Addizione in Riga e in Colonna", slug: "nvi4_mat_p027", view_template: "nvi4_mat_p027", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 28, titolo: "Le Proprietà dell'Addizione", slug: "nvi4_mat_p028", view_template: "nvi4_mat_p028", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 29, titolo: "L'Addizione: Strategie di Calcolo", slug: "nvi4_mat_p029", view_template: "nvi4_mat_p029", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 30, titolo: "La Sottrazione", slug: "nvi4_mat_p030", view_template: "nvi4_mat_p030", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 31, titolo: "La Sottrazione in Riga e in Colonna", slug: "nvi4_mat_p031", view_template: "nvi4_mat_p031", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 32, titolo: "La Proprietà della Sottrazione", slug: "nvi4_mat_p032", view_template: "nvi4_mat_p032", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 33, titolo: "La Sottrazione: Strategie di Calcolo", slug: "nvi4_mat_p033", view_template: "nvi4_mat_p033", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 34, titolo: "Addizione o Sottrazione?", slug: "nvi4_mat_p034", view_template: "nvi4_mat_p034", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 35, titolo: "Addizione o Sottrazione?", slug: "nvi4_mat_p035", view_template: "nvi4_mat_p035", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 36, titolo: "Addizione e Sottrazione", slug: "nvi4_mat_p036", view_template: "nvi4_mat_p036", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 37, titolo: "L'Addizione e la Sottrazione", slug: "nvi4_mat_p037", view_template: "nvi4_mat_p037", sottotitolo: "MAPPA", base_color: "pink" },
  { numero: 38, titolo: "La Moltiplicazione", slug: "nvi4_mat_p038", view_template: "nvi4_mat_p038", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 39, titolo: "La Moltiplicazione in Riga e in Colonna", slug: "nvi4_mat_p039", view_template: "nvi4_mat_p039", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 40, titolo: "Le Proprietà della Moltiplicazione", slug: "nvi4_mat_p040", view_template: "nvi4_mat_p040", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 41, titolo: "La Moltiplicazione: Strategie di Calcolo", slug: "nvi4_mat_p041", view_template: "nvi4_mat_p041", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 42, titolo: "La Divisione", slug: "nvi4_mat_p042", view_template: "nvi4_mat_p042", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 43, titolo: "La Divisione in Riga e in Colonna", slug: "nvi4_mat_p043", view_template: "nvi4_mat_p043", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 44, titolo: "La Proprietà della Divisione", slug: "nvi4_mat_p044", view_template: "nvi4_mat_p044", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 45, titolo: "La Divisione: Strategie di Calcolo", slug: "nvi4_mat_p045", view_template: "nvi4_mat_p045", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 46, titolo: "La Moltiplicazione Araba", slug: "nvi4_mat_p046", view_template: "nvi4_mat_p046", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 47, titolo: "La Divisione Canadese", slug: "nvi4_mat_p047", view_template: "nvi4_mat_p047", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 48, titolo: "Moltiplicazione o Divisione?", slug: "nvi4_mat_p048", view_template: "nvi4_mat_p048", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 49, titolo: "Moltiplicazione o Divisione?", slug: "nvi4_mat_p049", view_template: "nvi4_mat_p049", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 50, titolo: "Moltiplicazione e Divisione", slug: "nvi4_mat_p050", view_template: "nvi4_mat_p050", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 51, titolo: "Moltiplicazione e Divisione", slug: "nvi4_mat_p051", view_template: "nvi4_mat_p051", sottotitolo: "MAPPA", base_color: "pink" },
  { numero: 52, titolo: "Multipli", slug: "nvi4_mat_p052", view_template: "nvi4_mat_p052", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 53, titolo: "Divisori, Divisibilità", slug: "nvi4_mat_p053", view_template: "nvi4_mat_p053", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 54, titolo: "Le Quattro Operazioni", slug: "nvi4_mat_p054", view_template: "nvi4_mat_p054", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 55, titolo: "Le Quattro Operazioni", slug: "nvi4_mat_p055", view_template: "nvi4_mat_p055", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 56, titolo: "Le Frazioni", slug: "nvi4_mat_p056", view_template: "nvi4_mat_p056", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 57, titolo: "I Termini della Frazione", slug: "nvi4_mat_p057", view_template: "nvi4_mat_p057", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 58, titolo: "L'Unità Frazionaria", slug: "nvi4_mat_p058", view_template: "nvi4_mat_p058", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 59, titolo: "La Frazione come Operatore", slug: "nvi4_mat_p059", view_template: "nvi4_mat_p059", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 60, titolo: "Frazioni Complementari", slug: "nvi4_mat_p060", view_template: "nvi4_mat_p060", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 61, titolo: "Frazioni Equivalenti", slug: "nvi4_mat_p061", view_template: "nvi4_mat_p061", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 62, titolo: "Frazioni Proprie, Improprie...", slug: "nvi4_mat_p062", view_template: "nvi4_mat_p062", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 63, titolo: "...e Apparenti", slug: "nvi4_mat_p063", view_template: "nvi4_mat_p063", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 64, titolo: "La Frazione di un Numero", slug: "nvi4_mat_p064", view_template: "nvi4_mat_p064", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 65, titolo: "Le Frazioni", slug: "nvi4_mat_p065", view_template: "nvi4_mat_p065", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 66, titolo: "Confronto tra Frazioni", slug: "nvi4_mat_p066", view_template: "nvi4_mat_p066", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 67, titolo: "Frazioni con Denominatore Uguale", slug: "nvi4_mat_p067", view_template: "nvi4_mat_p067", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 68, titolo: "Risolvere Problemi con le Frazioni", slug: "nvi4_mat_p068", view_template: "nvi4_mat_p068", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 69, titolo: "Risolvere Problemi con le Frazioni", slug: "nvi4_mat_p069", view_template: "nvi4_mat_p069", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 70, titolo: "Le Frazioni", slug: "nvi4_mat_p070", view_template: "nvi4_mat_p070", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 71, titolo: "La Frazione", slug: "nvi4_mat_p071", view_template: "nvi4_mat_p071", sottotitolo: "MAPPA", base_color: "pink" },
  { numero: 72, titolo: "Frazioni Decimali", slug: "nvi4_mat_p072", view_template: "nvi4_mat_p072", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 73, titolo: "I Numeri con la Virgola", slug: "nvi4_mat_p073", view_template: "nvi4_mat_p073", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 74, titolo: "I Numeri Decimali", slug: "nvi4_mat_p074", view_template: "nvi4_mat_p074", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 75, titolo: "Confrontare e Ordinare i Numeri Decimali", slug: "nvi4_mat_p075", view_template: "nvi4_mat_p075", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 76, titolo: "Moltiplicare per 10, 100, 1000", slug: "nvi4_mat_p076", view_template: "nvi4_mat_p076", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 77, titolo: "Dividere per 10, 100, 1000", slug: "nvi4_mat_p077", view_template: "nvi4_mat_p077", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 78, titolo: "Addizioni e Sottrazioni con i Decimali", slug: "nvi4_mat_p078", view_template: "nvi4_mat_p078", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 79, titolo: "Moltiplicazioni e Divisioni con i Decimali", slug: "nvi4_mat_p079", view_template: "nvi4_mat_p079", sottotitolo: "NUMERI", base_color: "pink" },
  { numero: 80, titolo: "I Numeri Decimali", slug: "nvi4_mat_p080", view_template: "nvi4_mat_p080", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 81, titolo: "Le Frazioni Decimali e i Numeri Decimali", slug: "nvi4_mat_p081", view_template: "nvi4_mat_p081", sottotitolo: "MAPPA", base_color: "pink" },
  { numero: 82, titolo: "Le Frazioni e i Numeri Decimali", slug: "nvi4_mat_p082", view_template: "nvi4_mat_p082", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 83, titolo: "Le Frazioni e i Numeri Decimali", slug: "nvi4_mat_p083", view_template: "nvi4_mat_p083", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 84, titolo: "I Dati e la Domanda", slug: "nvi4_mat_p084", view_template: "nvi4_mat_p084", sottotitolo: "RISOLVERE PROBLEMI", base_color: "pink" },
  { numero: 85, titolo: "Risolvere Problemi", slug: "nvi4_mat_p085", view_template: "nvi4_mat_p085", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 86, titolo: "Scegliere i Dati", slug: "nvi4_mat_p086", view_template: "nvi4_mat_p086", sottotitolo: "RISOLVERE PROBLEMI", base_color: "pink" },
  { numero: 87, titolo: "Risolvere Problemi", slug: "nvi4_mat_p087", view_template: "nvi4_mat_p087", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 88, titolo: "Rappresentare i Dati", slug: "nvi4_mat_p088", view_template: "nvi4_mat_p088", sottotitolo: "RISOLVERE PROBLEMI", base_color: "pink" },
  { numero: 89, titolo: "Risolvere Problemi", slug: "nvi4_mat_p089", view_template: "nvi4_mat_p089", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 90, titolo: "Quante Soluzioni?", slug: "nvi4_mat_p090", view_template: "nvi4_mat_p090", sottotitolo: "RISOLVERE PROBLEMI", base_color: "pink" },
  { numero: 91, titolo: "Problemi con Più Soluzioni", slug: "nvi4_mat_p091", view_template: "nvi4_mat_p091", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 92, titolo: "Misura", slug: "nvi4_mat_p092", view_template: "nvi4_mat_p092", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 93, titolo: "Unità di Misura e Sottomultipli", slug: "nvi4_mat_p093", view_template: "nvi4_mat_p093", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 94, titolo: "Le Misure", slug: "nvi4_mat_p094", view_template: "nvi4_mat_p094", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 95, titolo: "Le Misure di Lunghezza", slug: "nvi4_mat_p095", view_template: "nvi4_mat_p095", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 96, titolo: "Le Misure di Capacità", slug: "nvi4_mat_p096", view_template: "nvi4_mat_p096", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 97, titolo: "Le Misure di Massa", slug: "nvi4_mat_p097", view_template: "nvi4_mat_p097", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 98, titolo: "Lunghezza, Capacità e Massa", slug: "nvi4_mat_p098", view_template: "nvi4_mat_p098", sottotitolo: "ESERCIZI", base_color: "pink" },
  { numero: 99, titolo: "Le Misure", slug: "nvi4_mat_p099", view_template: "nvi4_mat_p099", sottotitolo: "MAPPA", base_color: "pink" },
  { numero: 100, titolo: "Peso Lordo, Peso Netto, Tara", slug: "nvi4_mat_p100", view_template: "nvi4_mat_p100", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 172, titolo: "Numeri fino alle Migliaia e Operazioni", slug: "nvi4_mat_p172", view_template: "nvi4_mat_p172", sottotitolo: "ESERCIZI - RIPASSO", base_color: "cyan" },
  { numero: 173, titolo: "I Numeri Grandi", slug: "nvi4_mat_p173", view_template: "nvi4_mat_p173", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 174, titolo: "Comporre e Scomporre (1)", slug: "nvi4_mat_p174", view_template: "nvi4_mat_p174", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 175, titolo: "Comporre e Scomporre (2)", slug: "nvi4_mat_p175", view_template: "nvi4_mat_p175", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 176, titolo: "Ordinare i Numeri", slug: "nvi4_mat_p176", view_template: "nvi4_mat_p176", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 177, titolo: "Confrontare i Numeri", slug: "nvi4_mat_p177", view_template: "nvi4_mat_p177", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 178, titolo: "I Numeri Grandi", slug: "nvi4_mat_p178", view_template: "nvi4_mat_p178", sottotitolo: "ESERCIZI - RIPASSO", base_color: "cyan" },
  { numero: 179, titolo: "L'Addizione in Riga e in Colonna", slug: "nvi4_mat_p179", view_template: "nvi4_mat_p179", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 180, titolo: "Le Proprietà dell'Addizione", slug: "nvi4_mat_p180", view_template: "nvi4_mat_p180", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 181, titolo: "Addizione: Calcoli Veloci", slug: "nvi4_mat_p181", view_template: "nvi4_mat_p181", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 182, titolo: "La Sottrazione in Riga e in Colonna", slug: "nvi4_mat_p182", view_template: "nvi4_mat_p182", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 183, titolo: "La Proprietà della Sottrazione", slug: "nvi4_mat_p183", view_template: "nvi4_mat_p183", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 184, titolo: "Sottrazione: Calcoli Veloci", slug: "nvi4_mat_p184", view_template: "nvi4_mat_p184", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 185, titolo: "Addizioni e Sottrazioni", slug: "nvi4_mat_p185", view_template: "nvi4_mat_p185", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 186, titolo: "Problemi con Addizioni e Sottrazioni", slug: "nvi4_mat_p186", view_template: "nvi4_mat_p186", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 187, titolo: "Addizione e Sottrazione", slug: "nvi4_mat_p187", view_template: "nvi4_mat_p187", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 188, titolo: "La Moltiplicazione in Riga e in Colonna", slug: "nvi4_mat_p188", view_template: "nvi4_mat_p188", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 189, titolo: "Le Proprietà della Moltiplicazione", slug: "nvi4_mat_p189", view_template: "nvi4_mat_p189", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 190, titolo: "La Divisione in Riga e in Colonna", slug: "nvi4_mat_p190", view_template: "nvi4_mat_p190", sottotitolo: "ESERCIZI", base_color: "cyan" }
].each do |pagina_data|
  nvi_matematica.pagine.create!(pagina_data)
end

# Storia
nvi_storia = nvi_volume4.discipline.create!(
  nome: "Storia",
  codice: "sto",
  colore: "#06B6D4"
)

[
  { numero: 154, titolo: "Le Conoscenze dei Babilonesi", slug: "nvi4_sto_p154", view_template: "nvi4_sto_p154" },
  { numero: 155, titolo: "Gli Ittiti", slug: "nvi4_sto_p155", view_template: "nvi4_sto_p155" }
].each do |pagina_data|
  nvi_storia.pagine.create!(pagina_data)
end

puts "  ✓ Creato volume '#{nvi_volume4.nome}' con #{nvi_matematica.pagine.count} pagine di matematica e #{nvi_storia.pagine.count} pagine di storia"

# 5. NUOVO VIVA IMPARARE 5
nvi_volume5 = nvi.volumi.create!(
  nome: "Nuovo Viva Imparare 5",
  classe: 5,
  posizione: 5
)

nvi5_matematica = nvi_volume5.discipline.create!(
  nome: "Matematica",
  codice: "mat",
  colore: "#A855F7"
)

[
  { numero: 1, titolo: "Copertina", slug: "nvi5_mat_p001", view_template: "nvi5_mat_p001", sottotitolo: "", base_color: "pink" },
  { numero: 2, titolo: "", slug: "nvi5_mat_p002", view_template: "nvi5_mat_p002", sottotitolo: "INDICE", base_color: "pink" },
  { numero: 3, titolo: "", slug: "nvi5_mat_p003", view_template: "nvi5_mat_p003", sottotitolo: "INDICE", base_color: "pink" },
  { numero: 4, titolo: "Numeri - Misura - Geometria", slug: "nvi5_mat_p004", view_template: "nvi5_mat_p004", sottotitolo: "PER RICOMINCIARE", base_color: "pink" },
  { numero: 5, titolo: "Le frazioni", slug: "nvi5_mat_p005", view_template: "nvi5_mat_p005", sottotitolo: "PER RICOMINCIARE", base_color: "pink" },
  { numero: 6, titolo: "Misura", slug: "nvi5_mat_p006", view_template: "nvi5_mat_p006", sottotitolo: "PER RICOMINCIARE", base_color: "pink" },
  { numero: 7, titolo: "Geometria", slug: "nvi5_mat_p007", view_template: "nvi5_mat_p007", sottotitolo: "PER RICOMINCIARE", base_color: "pink" },
  { numero: 8, titolo: "Numeri Potenze", slug: "nvi5_mat_p008", view_template: "nvi5_mat_p008", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 9, titolo: "Numeri Relativi", slug: "nvi5_mat_p009", view_template: "nvi5_mat_p009", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 10, titolo: "Numeri Molto Grandi", slug: "nvi5_mat_p010", view_template: "nvi5_mat_p010", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 11, titolo: "Diverse Scritture dei Numeri", slug: "nvi5_mat_p011", view_template: "nvi5_mat_p011", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 12, titolo: "I Numeri Romani", slug: "nvi5_mat_p012", view_template: "nvi5_mat_p012", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 13, titolo: "I Numeri Grandi", slug: "nvi5_mat_p013", view_template: "nvi5_mat_p013", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 14, titolo: "I Numeri Decimali", slug: "nvi5_mat_p014", view_template: "nvi5_mat_p014", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 15, titolo: "Arrotondamento o Approssimazione", slug: "nvi5_mat_p015", view_template: "nvi5_mat_p015", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 16, titolo: "Le Potenze", slug: "nvi5_mat_p016", view_template: "nvi5_mat_p016", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 17, titolo: "La Scrittura Polinomiale", slug: "nvi5_mat_p017", view_template: "nvi5_mat_p017", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 18, titolo: "I Numeri - Esercizi", slug: "nvi5_mat_p018", view_template: "nvi5_mat_p018", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 19, titolo: "Esercizi", slug: "nvi5_mat_p019", view_template: "nvi5_mat_p019" },
  { numero: 20, titolo: "I Numeri Interi Relativi", slug: "nvi5_mat_p020", view_template: "nvi5_mat_p020" },
  { numero: 21, titolo: "Confrontare e Ordinare i Numeri Interi Relativi", slug: "nvi5_mat_p021", view_template: "nvi5_mat_p021" },
  { numero: 22, titolo: "Operare con i Numeri Interi Relativi", slug: "nvi5_mat_p022", view_template: "nvi5_mat_p022" },
  { numero: 23, titolo: "La Calcolatrice", slug: "nvi5_mat_p023", view_template: "nvi5_mat_p023" },
  { numero: 24, titolo: "I Numeri Decimali e I Numeri Relativi", slug: "nvi5_mat_p024", view_template: "nvi5_mat_p024" },
  { numero: 25, titolo: "Mappa - Il Nostro Sistema di Numerazione", slug: "nvi5_mat_p025", view_template: "nvi5_mat_p025" },
  { numero: 26, titolo: "I Numeri", slug: "nvi5_mat_p026", view_template: "nvi5_mat_p026", sottotitolo: "VERIFICA", base_color: "cyan" },
  { numero: 27, titolo: "I Numeri", slug: "nvi5_mat_p027", view_template: "nvi5_mat_p027", sottotitolo: "MODELLO INVALSI", base_color: "red" },
  { numero: 28, titolo: "I Numeri - Verifica Avanzata", slug: "nvi5_mat_p028", view_template: "nvi5_mat_p028", sottotitolo: "MODELLO INVALSI", base_color: "red" },
  { numero: 29, titolo: "I Numeri - Esercizi Guidati", slug: "nvi5_mat_p029", view_template: "nvi5_mat_p029", sottotitolo: "MODELLO INVALSI", base_color: "red" },
  { numero: 30, titolo: "La Sottrazione", slug: "nvi5_mat_p030", view_template: "nvi5_mat_p030", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 31, titolo: "La Proprietà della Sottrazione", slug: "nvi5_mat_p031", view_template: "nvi5_mat_p031", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 32, titolo: "La Moltiplicazione", slug: "nvi5_mat_p032", view_template: "nvi5_mat_p032", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 33, titolo: "Moltiplicazioni con i Numeri Decimali", slug: "nvi5_mat_p033", view_template: "nvi5_mat_p033", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 34, titolo: "Le Proprietà della Moltiplicazione", slug: "nvi5_mat_p034", view_template: "nvi5_mat_p034", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 35, titolo: "La Divisione", slug: "nvi5_mat_p035", view_template: "nvi5_mat_p035", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 36, titolo: "Divisioni con i Numeri Decimali", slug: "nvi5_mat_p036", view_template: "nvi5_mat_p036", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 37, titolo: "La Proprietà della Divisione", slug: "nvi5_mat_p037", view_template: "nvi5_mat_p037", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 38, titolo: "Moltiplicare e Dividere Numeri Decimali", slug: "nvi5_mat_p038", view_template: "nvi5_mat_p038", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 39, titolo: "Strategie di Calcolo", slug: "nvi5_mat_p039", view_template: "nvi5_mat_p039", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 40, titolo: "Moltiplicazioni per 10, 100, 1000", slug: "nvi5_mat_p040", view_template: "nvi5_mat_p040", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 41, titolo: "Divisioni per 10, 100, 1000", slug: "nvi5_mat_p041", view_template: "nvi5_mat_p041", sottotitolo: "NUMERI", base_color: "blue" },
  { numero: 42, titolo: "Le Quattro Operazioni", slug: "nvi5_mat_p042", view_template: "nvi5_mat_p042", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 43, titolo: "Le Quattro Operazioni", slug: "nvi5_mat_p043", view_template: "nvi5_mat_p043", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 44, titolo: "Le Espressioni Aritmetiche", slug: "nvi5_mat_p044", view_template: "nvi5_mat_p044", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 45, titolo: "Espressioni e Problemi", slug: "nvi5_mat_p045", view_template: "nvi5_mat_p045", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 46, titolo: "Multipli e Divisori", slug: "nvi5_mat_p046", view_template: "nvi5_mat_p046", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 47, titolo: "Criteri di Divisibilità", slug: "nvi5_mat_p047", view_template: "nvi5_mat_p047", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 48, titolo: "I Numeri Primi e la Scomposizione in Fattori Primi", slug: "nvi5_mat_p048", view_template: "nvi5_mat_p048", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 49, titolo: "Espressioni, Divisibilità, Numeri Primi", slug: "nvi5_mat_p049", view_template: "nvi5_mat_p049", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 50, titolo: "Le Operazioni con i Decimali", slug: "nvi5_mat_p050", view_template: "nvi5_mat_p050", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 51, titolo: "Espressioni Aritmetiche", slug: "nvi5_mat_p051", view_template: "nvi5_mat_p051", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 52, titolo: "Operazioni e Relazioni tra Numeri", slug: "nvi5_mat_p052", view_template: "nvi5_mat_p052", sottotitolo: "VERIFICA", base_color: "cyan" },
  { numero: 53, titolo: "Operazioni e Relazioni tra Numeri", slug: "nvi5_mat_p053", view_template: "nvi5_mat_p053", sottotitolo: "MODELLO INVALSI", base_color: "red" },
  { numero: 54, titolo: "Le Frazioni", slug: "nvi5_mat_p054", view_template: "nvi5_mat_p054", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 55, titolo: "Frazioni Complementari ed Equivalenti", slug: "nvi5_mat_p055", view_template: "nvi5_mat_p055", sottotitolo: "NUMERI", base_color: "purple" },
  { numero: 56, titolo: "LE FRAZIONI", slug: "nvi5_mat_p056", view_template: "nvi5_mat_p056", sottotitolo: "ESERCIZI", base_color: "purple" },
  { numero: 57, titolo: "Frazioni Proprie, Improprie e Apparenti", slug: "nvi5_mat_p057", view_template: "nvi5_mat_p057" },
  { numero: 58, titolo: "Laboratorio - Ricostruiamo l'Intero", slug: "nvi5_mat_p058", view_template: "nvi5_mat_p058" },
  { numero: 59, titolo: "Laboratorio - Ricostruiamo l'Intero (Frazioni Qualsiasi)", slug: "nvi5_mat_p059", view_template: "nvi5_mat_p059" },
  { numero: 60, titolo: "Confrontiamo le Frazioni", slug: "nvi5_mat_p060", view_template: "nvi5_mat_p060", base_color: "purple" },
  { numero: 61, titolo: "Confrontare le Frazioni - Il Prodotto in Croce", slug: "nvi5_mat_p061", view_template: "nvi5_mat_p061" },
  { numero: 62, titolo: "Addizioni e Sottrazioni con le Frazioni", slug: "nvi5_mat_p062", view_template: "nvi5_mat_p062" },
  { numero: 63, titolo: "La Frazione come Operatore", slug: "nvi5_mat_p063", view_template: "nvi5_mat_p063" },
  { numero: 64, titolo: "Dalla Frazione all'Intero", slug: "nvi5_mat_p064", view_template: "nvi5_mat_p064" },
  { numero: 65, titolo: "Frazioni Decimali e Numeri Decimali", slug: "nvi5_mat_p065", view_template: "nvi5_mat_p065" },
  { numero: 66, titolo: "Confronti e Operazioni con le Frazioni", slug: "nvi5_mat_p066", view_template: "nvi5_mat_p066" },
  { numero: 67, titolo: "La Percentuale", slug: "nvi5_mat_p067", view_template: "nvi5_mat_p067" },
  { numero: 68, titolo: "LO SCONTO", sottotitolo: "NUMERI", slug: "nvi5_mat_p068", view_template: "nvi5_mat_p068", base_color: "purple" },
  { numero: 69, sottotitolo: "Esercizi", titolo: "LA PERCENTUALE", slug: "nvi5_mat_p069", view_template: "nvi5_mat_p069", base_color: "blue" },
  { numero: 70, sottotitolo: "Verifica", titolo: "FRAZIONI E PERCENTUALE", slug: "nvi5_mat_p070", view_template: "nvi5_mat_p070", base_color: "red" },
  { numero: 71, sottotitolo: "Modello INVALSI", titolo: "FRAZIONI E PERCENTUALE", slug: "nvi5_mat_p071", view_template: "nvi5_mat_p071", base_color: "pink" },
  { numero: 72, titolo: "Risolvere Problemi - Usare le Immagini", slug: "nvi5_mat_p072", view_template: "nvi5_mat_p072" },
  { numero: 73, titolo: "Esercizi - Risolvere Problemi", slug: "nvi5_mat_p073", view_template: "nvi5_mat_p073" },
  { numero: 74, titolo: "Riflettere sui Dati e sul Risultato", slug: "nvi5_mat_p074", view_template: "nvi5_mat_p074" },
  { numero: 75, titolo: "Problemi con Divisione", slug: "nvi5_mat_p075", view_template: "nvi5_mat_p075", sottotitolo: "RISOLVERE PROBLEMI", base_color: "orange" },
  { numero: 76, titolo: "TUTTOPROBLEMI", slug: "nvi5_mat_p076", view_template: "nvi5_mat_p076", sottotitolo: "RISOLVERE PROBLEMI", base_color: "green" },
  { numero: 77, titolo: "TUTTOPROBLEMI", slug: "nvi5_mat_p077", view_template: "nvi5_mat_p077", sottotitolo: "RISOLVERE PROBLEMI", base_color: "indigo" },
  { numero: 80, titolo: "LE MISURE DI LUNGHEZZA E DI CAPACITÀ", slug: "nvi5_mat_p080", view_template: "nvi5_mat_p080", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 81, titolo: "LE MISURE DI MASSA", slug: "nvi5_mat_p081", view_template: "nvi5_mat_p081", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 82, titolo: "LE EQUIVALENZE", slug: "nvi5_mat_p082", view_template: "nvi5_mat_p082", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 83, titolo: "LUNGHEZZA, CAPACITÀ E MASSA", slug: "nvi5_mat_p083", view_template: "nvi5_mat_p083", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 84, titolo: "LE MISURE DI VALORE", slug: "nvi5_mat_p084", view_template: "nvi5_mat_p084", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 85, titolo: "IL COMMERCIO", slug: "nvi5_mat_p085", view_template: "nvi5_mat_p085", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 86, titolo: "LE MISURE DI TEMPO", slug: "nvi5_mat_p086", view_template: "nvi5_mat_p086", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 87, titolo: "CALCOLARE CON LE MISURE DI TEMPO", slug: "nvi5_mat_p087", view_template: "nvi5_mat_p087", sottotitolo: "MISURA", base_color: "pink" },
  { numero: 88, titolo: "EURO, COMMERCIO E TEMPO", slug: "nvi5_mat_p088", view_template: "nvi5_mat_p088", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 89, titolo: "EURO, COMMERCIO E TEMPO", slug: "nvi5_mat_p089", view_template: "nvi5_mat_p089", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 90, titolo: "MISURE DI LUNGHEZZA, CAPACITÀ E MASSA", slug: "nvi5_mat_p090", view_template: "nvi5_mat_p090", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 91, titolo: "MISURE DI VALORE E DI TEMPO", slug: "nvi5_mat_p091", view_template: "nvi5_mat_p091", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 92, titolo: "MISURA", slug: "nvi5_mat_p092", view_template: "nvi5_mat_p092", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 93, titolo: "MISURA", slug: "nvi5_mat_p093", view_template: "nvi5_mat_p093", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 94, titolo: "GEOMETRIA", slug: "nvi5_mat_p094", view_template: "nvi5_mat_p094", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 95, titolo: "GEOMETRIA", slug: "nvi5_mat_p095", view_template: "nvi5_mat_p095", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 96, titolo: "LE RETTE", slug: "nvi5_mat_p096", view_template: "nvi5_mat_p096", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 97, titolo: "GLI ANGOLI", slug: "nvi5_mat_p097", view_template: "nvi5_mat_p097", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 98, titolo: "IL PIANO CARTESIANO", slug: "nvi5_mat_p098", view_template: "nvi5_mat_p098", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 99, titolo: "ISOMETRIE: LA SIMMETRIA", slug: "nvi5_mat_p099", view_template: "nvi5_mat_p099", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 100, titolo: "LA ROTAZIONE", slug: "nvi5_mat_p100", view_template: "nvi5_mat_p100", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 101, titolo: "LA TRASLAZIONE", slug: "nvi5_mat_p101", view_template: "nvi5_mat_p101", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 102, titolo: "LA SIMILITUDINE", slug: "nvi5_mat_p102", view_template: "nvi5_mat_p102", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 103, titolo: "ISOMETRIE E SIMILITUDINE", slug: "nvi5_mat_p103", view_template: "nvi5_mat_p103", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 104, titolo: "I POLIGONI", slug: "nvi5_mat_p104", view_template: "nvi5_mat_p104", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 105, titolo: "CLASSIFICARE I POLIGONI", slug: "nvi5_mat_p105", view_template: "nvi5_mat_p105", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 106, titolo: "I TRIANGOLI", slug: "nvi5_mat_p106", view_template: "nvi5_mat_p106", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 107, titolo: "I QUADRILATERI", slug: "nvi5_mat_p107", view_template: "nvi5_mat_p107", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 108, titolo: "GLI ANGOLI INTERNI DEI POLIGONI", slug: "nvi5_mat_p108", view_template: "nvi5_mat_p108", sottotitolo: "LABORATORIO", base_color: "yellow" },
  { numero: 109, titolo: "I POLIGONI", slug: "nvi5_mat_p109", view_template: "nvi5_mat_p109", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 110, titolo: "IL PERIMETRO DEI POLIGONI", slug: "nvi5_mat_p110", view_template: "nvi5_mat_p110", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 111, titolo: "IL PERIMETRO", slug: "nvi5_mat_p111", view_template: "nvi5_mat_p111", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 112, titolo: "DISEGNO GEOMETRICO", slug: "nvi5_mat_p112", view_template: "nvi5_mat_p112", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 113, titolo: "DISEGNO GEOMETRICO", slug: "nvi5_mat_p113", view_template: "nvi5_mat_p113", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 114, titolo: "CIRCONFERENZA E CERCHIO", slug: "nvi5_mat_p114", view_template: "nvi5_mat_p114", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 115, titolo: "GLI ELEMENTI DELLA CIRCONFERENZA E DEL CERCHIO", slug: "nvi5_mat_p115", view_template: "nvi5_mat_p115", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 116, titolo: "LA MISURA DELLA CIRCONFERENZA", slug: "nvi5_mat_p116", view_template: "nvi5_mat_p116", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 117, titolo: "I POLIGONI REGOLARI", slug: "nvi5_mat_p117", view_template: "nvi5_mat_p117", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 118, titolo: "APOTEMA E NUMERO FISSO DEI POLIGONI REGOLARI", slug: "nvi5_mat_p118", view_template: "nvi5_mat_p118", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 119, titolo: "CERCHIO, CIRCONFERENZA E POLIGONI REGOLARI", slug: "nvi5_mat_p119", view_template: "nvi5_mat_p119", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 120, titolo: "POLIGONI REGOLARI CON IL COMPASSO", slug: "nvi5_mat_p120", view_template: "nvi5_mat_p120", sottotitolo: "LABORATORIO", base_color: "yellow" },
  { numero: 121, titolo: "ESAGONO E OTTAGONO REGOLARI", slug: "nvi5_mat_p121", view_template: "nvi5_mat_p121", sottotitolo: "LABORATORIO", base_color: "yellow" },
  { numero: 122, titolo: "LE MISURE DI SUPERFICIE", slug: "nvi5_mat_p122", view_template: "nvi5_mat_p122", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 123, titolo: "L'AREA DEI PARALLELOGRAMMI", slug: "nvi5_mat_p123", view_template: "nvi5_mat_p123", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 124, titolo: "L'AREA DEL TRAPEZIO E DEL TRIANGOLO", slug: "nvi5_mat_p124", view_template: "nvi5_mat_p124", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 125, titolo: "L'AREA DEI POLIGONI REGOLARI", slug: "nvi5_mat_p125", view_template: "nvi5_mat_p125", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 126, titolo: "L'AREA DI POLIGONI IRREGOLARI", slug: "nvi5_mat_p126", view_template: "nvi5_mat_p126", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 127, titolo: "L'AREA DEL CERCHIO", slug: "nvi5_mat_p127", view_template: "nvi5_mat_p127", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 128, titolo: "L'AREA DELLE FIGURE IRREGOLARI", slug: "nvi5_mat_p128", view_template: "nvi5_mat_p128", sottotitolo: "LABORATORIO", base_color: "green" },
  { numero: 129, titolo: "L'AREA", slug: "nvi5_mat_p129", view_template: "nvi5_mat_p129", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 130, titolo: "PERIMETRI E AREE NEL QUOTIDIANO", slug: "nvi5_mat_p130", view_template: "nvi5_mat_p130", sottotitolo: "LABORATORIO", base_color: "green" },
  { numero: 131, titolo: "PERIMETRI E AREE NEL QUOTIDIANO", slug: "nvi5_mat_p131", view_template: "nvi5_mat_p131", sottotitolo: "LABORATORIO", base_color: "yellow" },
  { numero: 132, titolo: "PERIMETRO E AREA DEI POLIGONI", slug: "nvi5_mat_p132", view_template: "nvi5_mat_p132", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 133, titolo: "CIRCONFERENZA E CERCHIO", slug: "nvi5_mat_p133", view_template: "nvi5_mat_p133", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 134, titolo: "I SOLIDI", slug: "nvi5_mat_p134", view_template: "nvi5_mat_p134", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 135, titolo: "I SOLIDI DI ROTAZIONE", slug: "nvi5_mat_p135", view_template: "nvi5_mat_p135", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 136, titolo: "I SOLIDI", slug: "nvi5_mat_p136", view_template: "nvi5_mat_p136", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 137, titolo: "LO SVILUPPO SUL PIANO DEI SOLIDI", slug: "nvi5_mat_p137", view_template: "nvi5_mat_p137", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 138, titolo: "LA SUPERFICIE DEI SOLIDI", slug: "nvi5_mat_p138", view_template: "nvi5_mat_p138", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 139, titolo: "LA SUPERFICIE DEI SOLIDI", slug: "nvi5_mat_p139", view_template: "nvi5_mat_p139", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 140, titolo: "LE MISURE DI VOLUME", slug: "nvi5_mat_p140", view_template: "nvi5_mat_p140", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 141, titolo: "IL VOLUME DEL PARALLELEPIPEDO E DEL CUBO", slug: "nvi5_mat_p141", view_template: "nvi5_mat_p141", sottotitolo: "GEOMETRIA", base_color: "pink" },
  { numero: 142, titolo: "SUPERFICI E VOLUMI DEI SOLIDI", slug: "nvi5_mat_p142", view_template: "nvi5_mat_p142", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 143, titolo: "LA SUPERFICIE DEI SOLIDI", slug: "nvi5_mat_p143", view_template: "nvi5_mat_p143", sottotitolo: "MAPPA", base_color: "cyan" },
  { numero: 144, titolo: "FIGURE PIANE E SOLIDE", slug: "nvi5_mat_p144", view_template: "nvi5_mat_p144", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 145, titolo: "FIGURE PIANE E SOLIDE", slug: "nvi5_mat_p145", view_template: "nvi5_mat_p145", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 146, titolo: "RISPARMI SETTIMANALI", slug: "nvi5_mat_p146", view_template: "nvi5_mat_p146", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 147, titolo: "VITTORIA IN BLU", slug: "nvi5_mat_p147", view_template: "nvi5_mat_p147", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 148, titolo: "LA VACANZA", slug: "nvi5_mat_p148", view_template: "nvi5_mat_p148", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 149, titolo: "GLI ASSISTENTI DI VOLO", slug: "nvi5_mat_p149", view_template: "nvi5_mat_p149", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 150, titolo: "LO SCONTO", slug: "nvi5_mat_p150", view_template: "nvi5_mat_p150", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 151, titolo: "UNO SPAZIO PER GIOVANI", slug: "nvi5_mat_p151", view_template: "nvi5_mat_p151", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 152, titolo: "UNA PESATA DIFFICILE", slug: "nvi5_mat_p152", view_template: "nvi5_mat_p152", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 153, titolo: "UNA QUESTIONE DI TEMPI", slug: "nvi5_mat_p153", view_template: "nvi5_mat_p153", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 154, titolo: "L'ALLENAMENTO", slug: "nvi5_mat_p154", view_template: "nvi5_mat_p154", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 155, titolo: "LA STELLA", slug: "nvi5_mat_p155", view_template: "nvi5_mat_p155", sottotitolo: "PROBLEMI AL CENTRO", base_color: "pink" },
  { numero: 156, titolo: "RELAZIONI, DATI E PREVISIONI", slug: "nvi5_mat_p156", view_template: "nvi5_mat_p156", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 157, titolo: "RELAZIONI, DATI E PREVISIONI", slug: "nvi5_mat_p157", view_template: "nvi5_mat_p157", sottotitolo: "PAROLE AL CENTRO", base_color: "pink" },
  { numero: 158, titolo: "CLASSIFICARE", slug: "nvi5_mat_p158", view_template: "nvi5_mat_p158", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 159, titolo: "STABILIRE RELAZIONI", slug: "nvi5_mat_p159", view_template: "nvi5_mat_p159", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 160, titolo: "CLASSIFICAZIONI E RELAZIONI", slug: "nvi5_mat_p160", view_template: "nvi5_mat_p160", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 161, titolo: "L'INDAGINE STATISTICA", slug: "nvi5_mat_p161", view_template: "nvi5_mat_p161", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 162, titolo: "INDAGINE STATISTICA", slug: "nvi5_mat_p162", view_template: "nvi5_mat_p162", sottotitolo: "AGNESE SONATO", base_color: "pink" },
  { numero: 163, titolo: "INDAGINE STATISTICA", slug: "nvi5_mat_p163", view_template: "nvi5_mat_p163", sottotitolo: "AGNESE SONATO", base_color: "pink" },
  { numero: 164, titolo: "AREOGRAMMI E PERCENTUALI", slug: "nvi5_mat_p164", view_template: "nvi5_mat_p164", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 165, titolo: "IL GRAFICO CARTESIANO", slug: "nvi5_mat_p165", view_template: "nvi5_mat_p165", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 166, titolo: "MODA, MEDIA E MEDIANA", slug: "nvi5_mat_p166", view_template: "nvi5_mat_p166", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 167, titolo: "COMBINAZIONI E PERMUTAZIONI", slug: "nvi5_mat_p167", view_template: "nvi5_mat_p167", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 168, titolo: "LA PROBABILITÀ", slug: "nvi5_mat_p168", view_template: "nvi5_mat_p168", sottotitolo: "RELAZIONI, DATI E PREVISIONI", base_color: "pink" },
  { numero: 169, titolo: "STATISTICA E PROBABILITÀ", slug: "nvi5_mat_p169", view_template: "nvi5_mat_p169", sottotitolo: "ESERCIZI", base_color: "orange" },
  { numero: 170, titolo: "RELAZIONI, DATI E PREVISIONI", slug: "nvi5_mat_p170", view_template: "nvi5_mat_p170", sottotitolo: "VERIFICA", base_color: "pink" },
  { numero: 171, titolo: "RELAZIONI, DATI E PREVISIONI", slug: "nvi5_mat_p171", view_template: "nvi5_mat_p171", sottotitolo: "MODELLO INVALSI", base_color: "pink" },
  { numero: 172, titolo: "LE CARTE ELETTRONICHE", slug: "nvi5_mat_p172", view_template: "nvi5_mat_p172", sottotitolo: "Educazione finanziaria", base_color: "pink" },
  { numero: 173, titolo: "LA BANCA E IL CONTO CORRENTE", slug: "nvi5_mat_p173", view_template: "nvi5_mat_p173", sottotitolo: "Educazione finanziaria", base_color: "pink" },
  { numero: 174, titolo: "FINANZIAMENTO E INTERESSI", slug: "nvi5_mat_p174", view_template: "nvi5_mat_p174", sottotitolo: "Educazione finanziaria", base_color: "pink" },
  { numero: 175, titolo: "IL MIO QUADERNO DEGLI ESERCIZI", slug: "nvi5_mat_p175", view_template: "nvi5_mat_p175", sottotitolo: "INDICE", base_color: "cyan" },
  { numero: 176, titolo: "MILIONI E MILIARDI", slug: "nvi5_mat_p176", view_template: "nvi5_mat_p176", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 177, titolo: "SCRITTURE DIVERSE DEI NUMERI", slug: "nvi5_mat_p177", view_template: "nvi5_mat_p177", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 178, titolo: "CONFRONTARE E ORDINARE NUMERI GRANDI", slug: "nvi5_mat_p178", view_template: "nvi5_mat_p178", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 179, titolo: "NUMERI DECIMALI (1)", slug: "nvi5_mat_p179", view_template: "nvi5_mat_p179", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 180, titolo: "NUMERI DECIMALI (2)", slug: "nvi5_mat_p180", view_template: "nvi5_mat_p180", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 181, titolo: "LE POTENZE", slug: "nvi5_mat_p181", view_template: "nvi5_mat_p181", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 182, titolo: "I NUMERI INTERI RELATIVI", slug: "nvi5_mat_p182", view_template: "nvi5_mat_p182", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 183, titolo: "I NUMERI FINO AI MILIARDI, LE POTENZE, I NUMERI INTERI RELATIVI", slug: "nvi5_mat_p183", view_template: "nvi5_mat_p183", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 184, titolo: "L'ADDIZIONE", slug: "nvi5_mat_p184", view_template: "nvi5_mat_p184", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 185, titolo: "LE PROPRIETÀ DELL'ADDIZIONE", slug: "nvi5_mat_p185", view_template: "nvi5_mat_p185", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 186, titolo: "LA SOTTRAZIONE", slug: "nvi5_mat_p186", view_template: "nvi5_mat_p186", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 187, titolo: "LA PROPRIETÀ DELLA SOTTRAZIONE", slug: "nvi5_mat_p187", view_template: "nvi5_mat_p187", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 188, titolo: "MOLTIPLICAZIONI E DIVISIONI", slug: "nvi5_mat_p188", view_template: "nvi5_mat_p188", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 189, titolo: "MOLTIPLICAZIONI CON I NUMERI DECIMALI", slug: "nvi5_mat_p189", view_template: "nvi5_mat_p189", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 190, titolo: "LE PROPRIETÀ DELLA MOLTIPLICAZIONE", slug: "nvi5_mat_p190", view_template: "nvi5_mat_p190", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 191, titolo: "DIVISIONI CON I NUMERI DECIMALI", slug: "nvi5_mat_p191", view_template: "nvi5_mat_p191", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 192, titolo: "LA PROPRIETÀ DELLA DIVISIONE", slug: "nvi5_mat_p192", view_template: "nvi5_mat_p192", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 193, titolo: "MOLTIPLICARE E DIVIDERE PER 10, 100, 1000", slug: "nvi5_mat_p193", view_template: "nvi5_mat_p193", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 194, titolo: "PROBLEMI CON LE QUATTRO OPERAZIONI (1)", slug: "nvi5_mat_p194", view_template: "nvi5_mat_p194", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 195, titolo: "PROBLEMI CON LE QUATTRO OPERAZIONI (2)", slug: "nvi5_mat_p195", view_template: "nvi5_mat_p195", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 196, titolo: "ESPRESSIONI ARITMETICHE", slug: "nvi5_mat_p196", view_template: "nvi5_mat_p196", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 197, titolo: "MULTIPLI E DIVISORI", slug: "nvi5_mat_p197", view_template: "nvi5_mat_p197", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 198, titolo: "CRITERI DI DIVISIBILITÀ", slug: "nvi5_mat_p198", view_template: "nvi5_mat_p198", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 199, titolo: "NUMERI PRIMI", slug: "nvi5_mat_p199", view_template: "nvi5_mat_p199", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 200, titolo: "LE OPERAZIONI E LE ESPRESSIONI", slug: "nvi5_mat_p200", view_template: "nvi5_mat_p200", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 201, titolo: "I CRITERI DI DIVISIBILITÀ, I MULTIPLI, I DIVISORI E I NUMERI PRIMI", slug: "nvi5_mat_p201", view_template: "nvi5_mat_p201", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 202, titolo: "LE FRAZIONI", slug: "nvi5_mat_p202", view_template: "nvi5_mat_p202", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 203, titolo: "FRAZIONI COMPLEMENTARI", slug: "nvi5_mat_p203", view_template: "nvi5_mat_p203", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 204, titolo: "FRAZIONI EQUIVALENTI", slug: "nvi5_mat_p204", view_template: "nvi5_mat_p204", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 205, titolo: "CONFRONTARE FRAZIONI", slug: "nvi5_mat_p205", view_template: "nvi5_mat_p205", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 206, titolo: "DALL'INTERO ALLA FRAZIONE, DALLA FRAZIONE ALL'INTERO", slug: "nvi5_mat_p206", view_template: "nvi5_mat_p206", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 207, titolo: "PROBLEMI CON LE FRAZIONI", slug: "nvi5_mat_p207", view_template: "nvi5_mat_p207", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 208, titolo: "LE FRAZIONI", slug: "nvi5_mat_p208", view_template: "nvi5_mat_p208", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 209, titolo: "FRAZIONI E NUMERI DECIMALI", slug: "nvi5_mat_p209", view_template: "nvi5_mat_p209", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 210, titolo: "LA PERCENTUALE", slug: "nvi5_mat_p210", view_template: "nvi5_mat_p210", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 211, titolo: "LO SCONTO", slug: "nvi5_mat_p211", view_template: "nvi5_mat_p211", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 212, titolo: "PROBLEMI CON I DECIMALI E LA PERCENTUALE", slug: "nvi5_mat_p212", view_template: "nvi5_mat_p212", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 213, titolo: "FRAZIONI DECIMALI E NUMERI DECIMALI", slug: "nvi5_mat_p213", view_template: "nvi5_mat_p213", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 214, titolo: "LA PERCENTUALE E LO SCONTO", slug: "nvi5_mat_p214", view_template: "nvi5_mat_p214", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 215, titolo: "I DATI E LA DOMANDA", slug: "nvi5_mat_p215", view_template: "nvi5_mat_p215", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 216, titolo: "IL DIAGRAMMA A STRISCIA E I SEGMENTI", slug: "nvi5_mat_p216", view_template: "nvi5_mat_p216", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 217, titolo: "DALLA STRUTTURA DEL PROBLEMA ALL'ESPRESSIONE", slug: "nvi5_mat_p217", view_template: "nvi5_mat_p217", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 218, titolo: "I PROBLEMI", slug: "nvi5_mat_p218", view_template: "nvi5_mat_p218", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 219, titolo: "MISURE DI LUNGHEZZA", slug: "nvi5_mat_p219", view_template: "nvi5_mat_p219", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 220, titolo: "MISURE DI CAPACITÀ", slug: "nvi5_mat_p220", view_template: "nvi5_mat_p220", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 221, titolo: "MISURE DI MASSA", slug: "nvi5_mat_p221", view_template: "nvi5_mat_p221", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 222, titolo: "LUNGHEZZA, CAPACITÀ E MASSA", slug: "nvi5_mat_p222", view_template: "nvi5_mat_p222", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 223, titolo: "L'EURO", slug: "nvi5_mat_p223", view_template: "nvi5_mat_p223", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 224, titolo: "IL COMMERCIO", slug: "nvi5_mat_p224", view_template: "nvi5_mat_p224", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 225, titolo: "MISURE DI TEMPO", slug: "nvi5_mat_p225", view_template: "nvi5_mat_p225", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 226, titolo: "PROBLEMI DI MISURA E DI COMPRAVENDITA", slug: "nvi5_mat_p226", view_template: "nvi5_mat_p226", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 227, titolo: "LE MISURE", slug: "nvi5_mat_p227", view_template: "nvi5_mat_p227", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 228, titolo: "RETTE, SEMIRETTE E SEGMENTI", slug: "nvi5_mat_p228", view_template: "nvi5_mat_p228", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 229, titolo: "ANGOLI", slug: "nvi5_mat_p229", view_template: "nvi5_mat_p229", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 230, titolo: "SIMMETRIA", slug: "nvi5_mat_p230", view_template: "nvi5_mat_p230", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 231, titolo: "ROTAZIONE", slug: "nvi5_mat_p231", view_template: "nvi5_mat_p231", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 232, titolo: "TRASLAZIONE", slug: "nvi5_mat_p232", view_template: "nvi5_mat_p232", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 233, titolo: "RIDUZIONI E INGRANDIMENTI IN SCALA", slug: "nvi5_mat_p233", view_template: "nvi5_mat_p233", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 234, titolo: "LE ISOMETRIE", slug: "nvi5_mat_p234", view_template: "nvi5_mat_p234", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 235, titolo: "POLIGONI", slug: "nvi5_mat_p235", view_template: "nvi5_mat_p235", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 236, titolo: "CLASSIFICARE I POLIGONI", slug: "nvi5_mat_p236", view_template: "nvi5_mat_p236", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 237, titolo: "CLASSIFICARE I QUADRILATERI", slug: "nvi5_mat_p237", view_template: "nvi5_mat_p237", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 238, titolo: "GLI ANGOLI E I POLIGONI", slug: "nvi5_mat_p238", view_template: "nvi5_mat_p238", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 239, titolo: "LA CIRCONFERENZA E IL CERCHIO", slug: "nvi5_mat_p239", view_template: "nvi5_mat_p239", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 240, titolo: "MISURE DI SUPERFICIE", slug: "nvi5_mat_p240", view_template: "nvi5_mat_p240", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 241, titolo: "IL PERIMETRO", slug: "nvi5_mat_p241", view_template: "nvi5_mat_p241", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 242, titolo: "L'AREA DEI PARALLELOGRAMMI", slug: "nvi5_mat_p242", view_template: "nvi5_mat_p242", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 243, titolo: "L'AREA DEL TRIANGOLO E DEL TRAPEZIO", slug: "nvi5_mat_p243", view_template: "nvi5_mat_p243", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 244, titolo: "L'AREA DEI POLIGONI REGOLARI", slug: "nvi5_mat_p244", view_template: "nvi5_mat_p244", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 245, titolo: "L'AREA DEL CERCHIO", slug: "nvi5_mat_p245", view_template: "nvi5_mat_p245", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 246, titolo: "PROBLEMI DI PERIMETRO E DI AREA (1)", slug: "nvi5_mat_p246", view_template: "nvi5_mat_p246", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 247, titolo: "PROBLEMI DI PERIMETRO E DI AREA (2)", slug: "nvi5_mat_p247", view_template: "nvi5_mat_p247", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 248, titolo: "I PERIMETRI E LE AREE", slug: "nvi5_mat_p248", view_template: "nvi5_mat_p248", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 249, titolo: "PROBLEMI CON I POLIGONI E IL CERCHIO", slug: "nvi5_mat_p249", view_template: "nvi5_mat_p249", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 250, titolo: "PROBLEMI CON IL PESO E LE FIGURE", slug: "nvi5_mat_p250", view_template: "nvi5_mat_p250", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 251, titolo: "IL PERIMETRO E L'AREA", slug: "nvi5_mat_p251", view_template: "nvi5_mat_p251", sottotitolo: "RIPASSO", base_color: "cyan" },
  { numero: 252, titolo: "I SOLIDI", slug: "nvi5_mat_p252", view_template: "nvi5_mat_p252", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 253, titolo: "CUBO E PARALLELEPIPEDO", slug: "nvi5_mat_p253", view_template: "nvi5_mat_p253", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 254, titolo: "PRISMA E PIRAMIDE", slug: "nvi5_mat_p254", view_template: "nvi5_mat_p254", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 255, titolo: "IL CILINDRO", slug: "nvi5_mat_p255", view_template: "nvi5_mat_p255", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 256, titolo: "MISURE DI VOLUME", slug: "nvi5_mat_p256", view_template: "nvi5_mat_p256", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 257, titolo: "IL VOLUME DEL PARALLELEPIPEDO E DEL CUBO", slug: "nvi5_mat_p257", view_template: "nvi5_mat_p257", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 258, titolo: "CLASSIFICARE", slug: "nvi5_mat_p258", view_template: "nvi5_mat_p258", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 259, titolo: "RAPPRESENTARE DATI", slug: "nvi5_mat_p259", view_template: "nvi5_mat_p259", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 260, titolo: "AREOGRAMMI E PERCENTUALI", slug: "nvi5_mat_p260", view_template: "nvi5_mat_p260", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 261, titolo: "MODA, MEDIA E MEDIANA", slug: "nvi5_mat_p261", view_template: "nvi5_mat_p261", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 262, titolo: "PROBABILITÀ", slug: "nvi5_mat_p262", view_template: "nvi5_mat_p262", sottotitolo: "ESERCIZI", base_color: "cyan" },
  { numero: 263, titolo: "LA STATISTICA E LA PROBABILITÀ", slug: "nvi5_mat_p263", view_template: "nvi5_mat_p263", sottotitolo: "RIPASSO", base_color: "cyan" }
].each do |pagina_data|
  nvi5_matematica.pagine.create!(pagina_data)
end

puts "  ✓ Creato volume '#{nvi_volume5.nome}' con #{nvi5_matematica.pagine.count} pagine"
